// All user-facing strings — no hardcoded text in components

export const labels = {
  // Splash entry
  splash: {
    pulseCodeLabel: 'Pulse code',
    pulseCodePlaceholder: 'Enter your pulse code',
    pulseCodeError: "That code doesn\u2019t look right. Check your invitation email.",
    joinButton: 'Join session',
    loginButton: 'Log in',
    signUpButton: 'Sign up',
    backButton: 'Back',
  },

  // Auth — Login
  login: {
    title: 'Sign in to Pulse',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    submitButton: 'Sign in',
    appleButton: 'Continue with Apple',
    googleButton: 'Continue with Google',
    invalidCredentials: 'Incorrect email or password. Try again.',
    newPasswordRequired: 'Setting password for {email}',
    newPasswordLabel: 'New password',
    newPasswordSubmit: 'Set password',
    forgotPassword: 'Forgot password?',
    registrationSuccess: 'Account created. Check your email for a temporary password, then sign in below.',
  },

  // Auth — Register
  register: {
    title: 'Create your account',
    nameLabel: 'Name',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    submitButton: 'Create account',
    verificationTitle: 'Check your email',
    verificationDescription: 'We sent a temporary password to {email}.',
    verificationCodeLabel: 'Verification code',
    verifyButton: 'Verify',
    resendButton: 'Resend code',
    resendCooldown: 'Resend in {seconds}s',
    codeSent: 'Code resent. Check your inbox.',
    invalidCode: "That code isn't right. Check your email and try again.",
    expiredCode: 'That code has expired. Request a new one.',
    emailExists: 'An account with this email already exists.',
    signupClosed: 'Sign-up is currently closed.',
  },

  // Welcome
  welcome: {
    title: 'Welcome to Pulse',
    description:
      'Pulse helps you collect structured feedback on your work through guided AI-driven conversations. Invite reviewers, gather insights, and generate a consolidated Pulse Check — all in one place.',
    ctaButton: 'Create your first item',
    secondaryCta: 'Or explore an example first',
    documentTitle: 'Welcome — Pulse',
  },

  // Items
  items: {
    title: 'Items',
    documentTitle: 'Items — Pulse',
    emptyState: 'No items yet',
    newItemButton: 'New Item',
    inviteButton: 'Get Feedback',
    pulseCheckButton: 'Pulse Check',
    pulseCheckInProgress: 'Run Pulse Check',
    pulseCheckStart: 'Start Your Pulse Check',
    pulseCheckReview: 'Review Your Pulse Check',
    loadError: 'Something went wrong loading your items. Try again.',
    retryButton: 'Retry',
    statusDraft: 'Draft',
    statusActive: 'Active',
    statusClosed: 'Closed',
    statusRevised: 'Revised',
    sessionCount: '{count} sessions',
    closeDate: 'Closes',
    // Warmth — greeting and count-based heading
    greetingLine: 'What are we reviewing today?',
    headingWithCount: 'Getting a pulse on {count} item',
    headingWithCountPlural: 'Getting a pulse on {count} items',
    // Empty state
    emptyHeading: 'Nothing here yet.',
    emptyBody: 'Create your first item and invite reviewers to get a pulse on your work.',
    emptyCta: 'Create your first item',
    // Session invitation empty state
    inviteEmptyText: 'Get a pulse on your work — invite reviewers',
    inviteEmptySubtext: 'Share a link or pulse code and collect structured feedback.',
    // Example badge
    exampleBadge: 'Example',
  },

  // Item detail
  itemDetail: {
    newDocumentTitle: 'New Item — Pulse',
    editDocumentTitle: '{itemName} — Pulse',
    newHeading: 'New Item',
    editHeading: 'Edit Item',
    fieldName: 'Item name',
    fieldNamePlaceholder: 'Enter item name',
    fieldDescription: 'Feedback focus',
    fieldDescriptionHint: 'This guides the AI conversation. Be specific about what you want reactions to.',
    fieldDescriptionPlaceholder: 'Tell Pulse what kind of feedback you\u2019re looking for \u2014 this shapes the questions reviewers are asked.',
    fieldCloseDate: 'Close date',
    fieldContent: 'Content',
    fieldContentPlaceholder: 'Paste your content here (Markdown supported)',
    fieldContentHint: 'Paste content directly, upload a file, or both.',
    contentPasteLabel: 'Paste content',
    contentUploadLabel: 'Upload a document',
    uploadAcceptHint: 'Accepts .md, .txt, .pdf, .docx, .jpg, .jpeg, .png, .webp, .gif — max 10 MB. Uploading a new file replaces the previous one.',
    uploadChooseFile: 'Choose file',
    uploadStatusScanning: 'Scanning…',
    uploadStatusExtracting: 'Extracting…',
    uploadStatusReady: 'Ready',
    uploadStatusRejected: 'Rejected — threat detected',
    uploadStatusExtractionFailed: 'Extraction failed',
    uploadStatusUploading: 'Uploading…',
    uploadStatusError: 'Upload failed',
    saveButton: 'Save',
    cancelButton: 'Cancel',
    deleteButton: 'Delete item',
    lockedError: 'This item is locked and cannot be edited',
    saveError: 'Failed to save item. Please try again.',
    loadError: 'Failed to load item.',
    deleteConfirmTitle: 'Delete item',
    deleteConfirmMessage:
      'Are you sure you want to delete {itemName}? This will also delete all sessions, transcripts, and reports associated with this item.',
    deleteConfirmCancel: 'Cancel',
    deleteConfirmDelete: 'Delete',
    deleteError: 'Failed to delete item. Please try again.',
    readOnlyNotice: 'Items with active or completed sessions can\u2019t be edited to preserve the integrity of reviewer feedback. To make changes, create a new item.',
    exampleCallout: 'This is what a completed pulse check looks like. Create your own item to get started.',
    closeItemButton: 'Close item',
    closeItemConfirmTitle: 'Close item',
    closeItemConfirmMessage: 'Close \u201c{itemName}\u201d? This will block any new reviewers from entering. Reviewers already in a session can finish naturally.',
    closeItemConfirmCancel: 'Cancel',
    closeItemConfirmClose: 'Close item',
    closeItemSuccess: 'Item closed.',
    closeItemError: 'Failed to close item. Please try again.',
    cancelSessionButton: 'Cancel invite',
    cancelSessionError: 'Failed to cancel invitation.',
    cancelSessionSuccess: 'Invitation cancelled.',
    previewLink: 'Preview',
    previewAriaLabel: 'Preview {filename}',
    previewCloseAriaLabel: 'Close document preview',
    previewLoading: 'Loading document\u2026',
    previewError: "This document couldn\u2019t be loaded.",
    previewRetry: 'Try again',
    previewEmpty: 'No document to preview.',
    previewExtractedCaption: 'Showing extracted text.',
    previewDownloadOriginal: 'Download original',
    previewPdfFallback: 'Open PDF in new tab \u2192',
    previewNoText: 'No text could be extracted from this file.',
    // Preview session
    previewSessionButton: 'Preview',
    previewSessionLoading: 'Opening preview\u2026',
    previewSessionError: 'Preview couldn\u2019t be started. Try again.',
    previewSessionPopupBlocked: 'Preview opened in a new tab. If it didn\u2019t open, check your popup settings.',
    // Time limit
    timeLimitLabel: 'Session time',
    timeLimitHint: 'This is a pacing estimate for Pulse — not a hard cutoff. The agent will naturally wrap up around this time, but reviewers can always finish their thought.',
    timeLimitBrackets: [
      { label: '5–10 min', value: 7 },
      { label: '10–15 min', value: 12 },
      { label: '15–20 min', value: 17 },
      { label: '20–30 min', value: 25 },
      { label: '30–45 min', value: 37 },
    ] as const,
    // Self-review session
    selfReviewButton: 'Review it yourself',
    selfReviewLoading: 'Starting\u2026',
    selfReviewError: 'Couldn\u2019t start your review. Try again.',
    selfReviewLimitError: 'You\u2019ve reached the session limit for this item.',
    selfReviewTooltip: 'Give yourself feedback on this item. Your session won\u2019t count toward reviewer limits.',
    selfReviewExistsNotice: 'You already have a review for this item.',
    selfReviewStartOver: 'Start over',
    selfReviewStartOverCancel: 'Cancel',
    analyzingDocument: 'Analyzing your document\u2026',
    analysisTimeout: 'Analysis is taking longer than expected.',
    sessionCapWarning: '{used} of {max} sessions used',
  },

  // Invitation section (within ItemDetail)
  invitation: {
    sectionTitle: 'Reviewers',
    emailsLabel: 'Invite reviewers',
    emailsPlaceholder: 'email@example.com, another@example.com',
    emailsHint: 'Separate multiple emails with commas.',
    inviteButton: 'Invite Reviewers',
    inviting: 'Inviting…',
    inviteSuccess: 'Invitations sent.',
    inviteError: 'Failed to send invitations. Please try again.',
    inviteLimitError: 'Session limit reached for this item.',
    publicSessionLimitHint: 'Up to {max} reviewers can participate',
    noSessions: 'No reviewers invited yet.',
    resendButton: 'Resend',
    resending: 'Resending…',
    resendSuccess: 'Invitation resent.',
    resendError: 'Failed to resend invitation.',
    statusNotStarted: 'Not started',
    statusInProgress: 'In progress',
    statusCompleted: 'Completed',
    statusExpired: 'Expired',
    statusDiscarded: 'Not started',
    extendDeadlineTitle: 'Change deadline',
    extendDeadlineLabel: 'New close date',
    extendDeadlineButton: 'Save',
    extending: 'Saving…',
    extendSuccess: 'Deadline updated.',
    extendError: 'Failed to update deadline.',
    viewReportButton: 'View Report',
    publicSessionTitle: 'Start Public Session',
    publicSessionDescription: 'For use at events, tables, or group settings where a single code is shared.',
    publicSessionDeadlineLabel: 'Session deadline',
    publicSessionGenerateButton: 'Generate',
    publicSessionGenerating: 'Generating…',
    publicSessionDoneButton: 'Done',
    publicSessionError: 'Failed to generate public session. Please try again.',
    publicSessionDownloadQr: 'Download QR code',
    publicSessionViewQr: 'View QR',
    publicSessionHideQr: 'Hide',
    publicSessionBadge: 'Public session',
    publicSessionQrError: 'Failed to load QR code. Try again.',
    closeButton: 'Close',
    publicSessionSectionTitle: 'Public Sessions',
    publicSessionNameLabel: 'Session name',
    publicSessionNamePlaceholder: 'e.g. Design Week Table',
    publicSessionNameHint: 'Optional — helps identify this session if you create multiple.',
    publicSessionEndButton: 'End session',
    publicSessionEnding: 'Ending\u2026',
    publicSessionEndError: 'Failed to end session. Try again.',
    publicSessionEndSuccess: 'Session ended.',
    publicSessionEndsLabel: 'Ends',
    noPublicSessions: 'No public sessions yet.',
  },

  // Settings
  settings: {
    title: 'Settings',
    documentTitle: 'Settings — Pulse',
    accountSection: 'Account',
    accountActionsHeading: 'Account actions',
    contactButton: 'Contact us',
    tierLabel: 'Plan',
    tierFree: 'Free',
    emailLabel: 'Email',
    displayNameLabel: 'Display name',
    displayNameAdd: 'Add name…',
    displayNamePlaceholder: 'Your name',
    usageSection: 'Usage',
    loading: 'Loading…',
    itemsLabel: 'Items',
    sessionsLabel: 'Sessions',
    itemsUsage: '{used} of {max}',
    sessionsUsage: '{used} of {max}',
    themeSection: 'Appearance',
    themeLabel: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    themeSaving: 'Saving…',
    themeSaved: 'Saved',
    signOutButton: 'Sign out',
    deleteAccountButton: 'Delete account',
    deleteAccountConfirm: 'Confirm — delete my account',
    deleteAccountDeleting: 'Deleting…',
    deleteAccountHint: 'This will permanently delete your account and all data.',
    deleteAccountConfirmHint: 'This cannot be undone. Click again to confirm.',
    // S6 additions
    editButton: 'Edit',
    saveButton: 'Save',
    cancelButton: 'Cancel',
    savingName: 'Saving…',
    savedName: 'Saved',
    changePasswordHeading: 'Password',
    currentPasswordLabel: 'Current password',
    newPasswordLabel: 'New password',
    updatePasswordButton: 'Update Password',
    updatingPassword: 'Updating…',
    passwordUpdated: 'Password updated.',
    dangerZoneHeading: 'Danger Zone',
    dangerZoneDescription: 'Permanently delete your account and all associated data. This cannot be undone.',
    deleteModalHeading: 'Delete your account',
    deleteModalBody: 'This will permanently delete all your items, sessions, transcripts, reports, pulse checks, and uploaded files. Your account cannot be recovered.',
    deleteEmailLabel: 'Type your email address to confirm',
    deleteConfirmButton: 'Delete Account',
    deleteLoadingButton: 'Deleting your account…',
    deleteCancelButton: 'Cancel',
    deleteServerError: 'Something went wrong. Please try again.',
    wrongCurrentPassword: "That password isn't correct.",
    newPasswordSameAsCurrent: 'New password must be different from your current password.',
    passwordTooShort: 'Password must be at least 8 characters.',
    passwordMissingUppercase: 'Password must include at least one uppercase letter.',
    passwordMissingNumber: 'Password must include at least one number.',
    passwordMissingSymbol: 'Password must include at least one symbol.',
    passwordGenericError: 'Something went wrong. Please try again.',
  },

  // Plan
  plan: {
    title: 'Plan',
    documentTitle: 'Plan — Pulse',
    tierLabel: 'Current plan',
    featuresHeading: 'Features',
    usageHeading: 'Usage',
    featureAllowed: 'Included',
    featureLocked: 'Locked',
    featureMaintenance: 'Maintenance',
    upgradeButton: 'Upgrade',
    // Billing (S4)
    upgradeToIndividual: 'Upgrade to Individual',
    upgradeToPro: 'Upgrade to Pro',
    upgradeToEnterprise: 'Upgrade to Enterprise',
    manageBilling: 'Manage Billing',
    changePlan: 'Change Plan',
    upgradeDisabledNoStripe: 'Billing setup incomplete. Contact support.',
    upgradeSuccess: 'Plan upgraded successfully!',
    periodLabel: 'Billing period',
    resetDateLabel: 'Resets',
    monthlyLimitReached: 'Monthly limit reached. Resets {resetDate}. Upgrade for more.',
    monthlyLimitNear: 'You have {remaining} left this month. Resets {resetDate}.',
  },

  // Feedback
  feedback: {
    summaryPrompt: 'Was this summary helpful?',
    pulseCheckPrompt: 'Did this help you decide what to do next?',
    reasonPromptSummary: 'What was off?',
    reasonPromptPulseCheck: 'What could be better?',
    thanks: 'Thanks',
    summaryDidntCapture: "Didn't capture what I said",
    summaryFeltGeneric: 'Felt generic',
    summaryLeftOutImportant: 'Left out the important parts',
    summaryWouldntShare: "I wouldn't share this",
    pcAlreadyKnew: 'I already knew this',
    pcTooAbstract: 'Too abstract to act on',
    pcDidntReflectReviewers: "Didn't reflect what reviewers told me",
    pcNeedMoreFeedback: 'Need more feedback first',
  },

  // Layout
  layout: {
    navItems: 'Items',
    navPulseCheck: 'Pulse Check',
    navPlan: 'Plan',
    navSettings: 'Settings',
    logoAlt: 'ur/gd',
    wordmark: 'pulse',
    themeToggleLight: 'Switch to light mode',
    themeToggleDark: 'Switch to dark mode',
    avatarAlt: 'Account',
  },

  // Protected route
  protectedRoute: {
    redirecting: 'Redirecting to login…',
  },

  // Session report
  sessionReport: {
    documentTitle: 'Session Report — Pulse',
    documentTitleLoading: 'Loading Report — Pulse',
    loading: 'Loading report…',
    loadError: 'This report couldn\'t be loaded. The session may not be completed yet.',
    backToItem: 'Back to item',
    pulseFromReviewer: 'Here\'s the pulse from {reviewerLabel}',
    verdictLabel: 'Verdict',
    energyLabel: 'Overall energy',
    convictionsHeading: 'What Landed',
    tensionsHeading: 'Where It Struggled',
    uncertaintiesHeading: 'Open Questions',
    noConvictions: 'No strong convictions recorded.',
    noTensions: 'No significant tensions recorded.',
    noUncertainties: 'No open questions recorded.',
    generatedAt: 'Generated {date}',
    downloadPdf: 'Download PDF',
    downloadingPdf: 'Generating PDF…',
  },
  revision: {
    documentTitle: 'Revision — {itemName} — Pulse',
    backLink: '← Back to {itemName}',
    heading: 'Revision',
    headingWithNumber: 'Revision {number}',
    loading: 'Loading revisions…',
    emptyEyebrow: 'Ready to close the loop?',
    emptyHeading: 'Generate a revision from your decisions',
    emptyBody: 'Pulse will rewrite {itemName} based on the themes you accepted and revised. Your original document is preserved.',
    emptyWarning: 'Requires at least one Accept or Revise decision',
    emptyCta: 'Generate Revision',
    noPulseCheckBody: 'Run a Pulse Check first to generate decisions, then come back here.',
    noPulseCheckLink: 'Go to Pulse Check →',
    overlayPhase1: 'Calibrating signal…',
    overlayPhase2: 'Reading the original…',
    overlayPhase3: 'Tracing new signal…',
    overlayPhase4: 'Verifying returns…',
    overlayPhase5: 'Locking signal…',
    overlayPhase6: 'Finalizing…',
    overlayNotice: 'This usually takes 30–60 seconds. Don\u2019t close this tab.',
    originalPaneLabel: 'Original',
    revisionPaneLabel: 'Revision {number}',
    generateAnother: 'Generate Another Revision',
    historyLink: 'Revision History',
    generateError: 'Something went wrong generating the revision. Try again.',
    noPulseCheckError: 'Run a Pulse Check and save decisions before generating a revision.',
    loadError: 'Something went wrong loading revisions.',
    retryButton: 'Try again',
    downloadPdf: 'Download PDF',
    downloadingPdf: 'Generating PDF…',
  },

  // Forgot password
  forgotPassword: {
    documentTitle: 'Reset Password — Pulse',
    heading: 'Reset your password',
    subheading: "Enter your email and we'll send you a reset code.",
    emailLabel: 'Email',
    sendCodeButton: 'Send Reset Code',
    backToSignIn: 'Back to sign in',
    codeSentCaption: 'We sent a code to {email}. Check your inbox.',
    codeLabel: 'Verification code',
    newPasswordLabel: 'New password',
    setPasswordButton: 'Set New Password',
    resendCode: 'Resend code',
    codeResent: 'Code resent.',
    successHeading: 'Password updated.',
    successBody: 'You can now sign in with your new password.',
    successCta: 'Back to sign in',
    errorEmailNotFound: "We couldn't find an account with that email.",
    errorInvalidCode: "That code isn't right or has expired. Request a new one.",
    errorPasswordTooShort: 'Password must be at least 8 characters.',
    errorPasswordUppercase: 'Password must include at least one uppercase letter.',
    errorPasswordNumber: 'Password must include at least one number.',
    errorPasswordSymbol: 'Password must include at least one symbol.',
    errorTooManyAttempts: 'Too many attempts. Please wait a few minutes and try again.',
    errorGeneric: 'Something went wrong. Please try again.',
  },

  // Pulse check
  pulseCheck: {
    documentTitle: '{itemName} — Pulse Check',
    documentTitleDefault: 'Pulse Check — Pulse',
    loading: 'Loading pulse check…',
    heading: 'Pulse Check',
    itemHeading: 'The pulse on {itemName}',
    backToItem: 'Back to item',
    incompleteSessionsNotice: '{incomplete} of {total} reviewers didn\u2019t finish — their partial feedback is included.',
    generatePromptText: 'All sessions are closed. Run a Pulse Check to consolidate feedback into a single view.',
    closeAndRunPromptText: 'Closing this item will stop new reviewers from entering and run your Pulse Check.',
    closeAndRunEyebrow: 'Ready to wrap up?',
    closeAndRunWarning: 'Any reviewers currently in a session won\u2019t be cut off \u2014 they can still finish. If sessions complete after you run, you can re-run the Pulse Check to include them.',
    closeAndRunButton: 'Close & Run Pulse Check',
    closeAndRunError: 'Something went wrong. Try again.',
    generateButton: 'Run Pulse Check',
    pulseCheckCta: 'It\u2019s time to check the pulse on {itemName}',
    generating: 'Generating…',
    overlayPhase1: 'Initiating signal…',
    overlayPhase2: 'Reading the wave…',
    overlayPhase3: 'Processing returns…',
    overlayPhase4: 'Mapping signal patterns…',
    overlayPhase5: 'Consolidating returns…',
    overlayPhase6: 'Locking signal…',
    overlayNotice: 'Don\u2019t close this tab — your Pulse Check is being generated.',
    generateError: 'Failed to generate pulse check. Please try again.',
    sessionsStillOpenError: 'Not all sessions are closed. Wait for remaining sessions to complete or expire.',
    verdictLabel: 'Verdict',
    energyLabel: 'Overall energy',
    noVerdict: 'No verdict available.',
    verdictPositive: 'Strong consensus — move forward',
    verdictNeutral: 'Mixed perspectives — review the gaps',
    verdictNegative: 'Not enough to go on — gather more input',
    askedForLabel: 'You asked for a pulse on',
    convictionsHeading: 'What Landed',
    tensionsHeading: 'Where It Struggled',
    questionsHeading: 'Open Questions',
    noConvictions: 'No shared convictions recorded.',
    noTensions: 'No repeated tensions recorded.',
    noQuestions: 'No open questions recorded.',
    matrixHeading: 'Signal Matrix',
    matrixAriaLabel: 'Cross-reviewer feedback signal matrix',
    synthesisHeading: 'What Surfaced',
    decisionsHeading: 'Proposed Revisions',
    decisionsHint: 'Mark each proposal — decisions are saved and used when you generate a revision.',
    noProposedRevisions: 'No revisions proposed — reviewers were largely aligned.',
    revisionTypeLabels: {
      structural: 'Structural',
      'line-edit': 'Line Edits',
      conceptual: 'Conceptual',
      feature: 'Features',
    },
    saveDecisionsButton: 'Save Decisions',
    savingDecisions: 'Saving…',
    decisionsSaved: 'Decisions saved.',
    saveDecisionsError: 'Failed to save decisions. Please try again.',
    generatedAt: 'Generated {date}',
    rerunButton: 'Re-run Pulse Check',
    rerunNote: 'Re-running will incorporate any sessions that completed since the last run.',
    rerunError: 'Failed to re-run pulse check. Please try again.',
    newSessionsNotice: '{count} reviewer(s) finished after this was generated — re-run to include their feedback.',
    downloadPdf: 'Download PDF',
    downloadingPdf: 'Generating PDF…',
    // Index empty state
    indexEmptyHeading: 'Select an item to view its Pulse Check.',
    indexGoToItems: 'Go to Items →',
    // Signal matrix
    matrixSignalDistribution: 'Signal distribution',
    matrixTheme: 'Theme',
    matrixShowQuote: 'Show quote',
    matrixHideQuote: 'Hide',
    // Signal summary
    topQuotesHeading: 'Top quotes',
    // Overlay error
    overlayErrorHeading: 'Something went wrong.',
    // S4 enhancements
    confidenceSolo: 'Based on 1 reviewer',
    confidenceMulti: 'Based on {count} reviewers',
    scaleSolo: 'Solo',
    scaleSmallGroup: 'Small Group',
    scaleMediumGroup: 'Medium Group',
    revisionWeight: '{count} of {total} reviewers flagged this',
    revisionWeightSolo: '1 reviewer flagged this',
    batchAcceptAll: 'Accept All',
    batchDismissAll: 'Dismiss All',
    batchUndo: 'Undo',
    viewRevisions: 'View Revisions',
    generateRevision: 'Generate Revision',
  },

  // Support / Report Modal (Task 37)
  support: {
    sectionHeading: 'Support',
    contactLink: 'Contact support',
    bugLink: 'Report a bug',
    featureLink: 'Request a feature',
    privacySectionHeading: 'Privacy',
    privacyLink: 'Privacy question',
  },

  // Terms of Service gate (Task 39)
  termsGate: {
    headingFirst: 'Before you continue, please review our Terms of Use.',
    headingUpdated: "We've updated our Terms of Use.",
    body: 'By clicking "I agree" you confirm you\'ve read and accept the full Terms of Use.',
    readLink: 'Read the full Terms of Use →',
    agreeButton: 'I agree and continue',
    agreeing: 'Saving…',
  },

  reportModal: {
    titleContactSupport: 'Contact support',
    titleBugReport: 'Report a bug',
    titleFeatureRequest: 'Request a feature',
    titlePrivacyQuestion: 'Privacy question',
    typeLabel: 'Type',
    messageLabel: 'Message',
    messagePlaceholder: 'Describe your issue or question.',
    nameLabel: 'Your name (optional)',
    emailLabel: 'Your email (optional)',
    emailHelper: "We'll use this to follow up if needed.",
    submitButton: 'Submit',
    submittingButton: 'Submitting…',
    successMessage: 'Your report has been sent.',
    errorMessage: "Couldn't send your report. Try again.",
    charLimitWarning: '{remaining} characters remaining',
    charLimitExceeded: 'Message must be 5,000 characters or fewer',
  },

  // Error boundary
  errorBoundary: {
    heading: 'Signal lost',
    body: 'Something unexpected happened. You can try reloading the page or go back to the items list.',
    reloadButton: 'Reload',
    goHomeLink: 'Go Home',
  },

  // Session timeout modal
  sessionTimeout: {
    heading: 'Session expiring',
    body: 'Your session will expire due to inactivity.',
    countdown: 'Time remaining: {seconds}s',
    extendButton: 'Extend Session',
    signOutButton: 'Sign Out',
  },

  // Sections (SectionPanel)
  sections: {
    sectionPanelTitle: 'Document Sections',
    keySection: 'Key section',
    supporting: 'Supporting',
    includeToggle: 'Include in feedback',
    depthDeep: 'Deep',
    depthExplore: 'Explore',
    depthSkim: 'Skim',
    validationAllExcluded: 'At least one section must be included.',
    analyzing: 'Analyzing document sections…',
    noSections: 'No sections detected.',
    coveragePanelTitle: 'Sections you asked reviewers to cover',
    coveragePartial: 'Reviewers covered {covered} of {total} requested sections.',
    coverageFull: 'Reviewers touched on every section you requested.',
  },

  // Assessment Helper
  assessmentHelper: {
    trigger: '💡 Help me with this',
    generateButton: 'Generate',
    generateDisabledTooltip: 'Save the item first to enable AI suggestions.',
    useThis: 'Use This',
    editFirst: 'Edit First',
    noInputMessage: 'Add some text or upload a document first so Pulse can generate a suggestion.',
    panelDescription: 'Pulse can read your document and craft a focused feedback request for you. Tap Generate to try it.',
    hintNoDocNoInput: 'Upload your document above, then describe what kind of feedback you\u2019re looking for. Pulse will use both to craft a focused request.',
    hintDocNoInput: 'What aspect of your work do you want feedback on? Even a rough note helps Pulse tailor the suggestion.',
    hintInputNoDoc: 'For the best results, upload your document too \u2014 Pulse reads it to ground the suggestion in your actual content.',
    generating: 'Generating…',
    errorMessage: 'Couldn\u2019t generate a suggestion. Try writing it yourself, or try again.',
    staticExamplesDocument: [
      'I\u2019d like feedback from a potential user on whether the value proposition is clear.',
      'From a non-technical perspective, is the structure logical and easy to follow?',
      'As a stakeholder, what\u2019s your honest reaction to the tone and approach?',
      'Does the argument build convincingly, or are there gaps that weaken the conclusion?',
      'If you had to summarize the key takeaway in one sentence, what would it be?',
      'Are the recommendations specific enough to act on, or do they feel vague?',
    ],
    staticExamplesImage: [
      'From a client\u2019s perspective, what\u2019s your first impression of this space?',
      'As someone seeing this for the first time, does the composition draw you in?',
      'From a buyer\u2019s point of view, is there anything that feels off or out of place?',
      'Does this align with the brand identity you\u2019d expect, or does it feel disconnected?',
      'What emotional response does this evoke, and is that the right one for the audience?',
      'If this were competing for attention alongside similar work, what would make it stand out?',
    ],
  },

  // Streaming
  streaming: {
    errorRetry: 'Something went wrong. Tap to retry.',
    errorTimeout: 'No response received. Tap to retry.',
    concurrentRequest: 'Please wait for the current response.',
  },

  // Completion
  completion: {
    cardTitle: 'Your signal has been received. Thanks for sharing your perspective.',
    emailCta: 'Get a copy of your session summary',
  },

  // Image session
  imageSession: {
    viewPhoto: '📷 View Photo',
    expandLabel: 'Expand photo',
    collapseLabel: 'Collapse photo',
  },

  // Data retention disclosure
  retention: {
    notice: 'Session transcripts are automatically deleted 30 days after a Pulse Check is generated. Reports, pulse checks, and your uploaded documents are retained until you delete the item or your account. Documents and images are archived to long-term storage after one year.',
    shortNotice: 'Transcripts are deleted 30 days after the Pulse Check is generated.',
    archiveNotice: 'Documents and images are archived to long-term storage after one year. Your content is never deleted automatically.',
    settingsHeading: 'Data Retention',
  },

  // About Pulse
  about: {
    button: 'About Pulse',
    version: 'Version {version}',
    descriptionP1: 'Pulse is a feedback tool. You upload your work, invite people to review it, and Pulse guides each conversation so you get structured, thoughtful feedback \u2014 not just \u201clooks good.\u201d',
    descriptionP2: 'When your reviewers are done, Pulse consolidates everything into a single view called a Pulse Check. It shows you what landed, where things struggled, and what to do next \u2014 so you can make decisions, not just collect opinions.',
    attribution: 'Quietly Powerful, by',
    attributionStudio: 'ur/gd Studios',
    attributionLocation: 'Seattle, WA',
    attributionUrl: 'https://urgdstudios.com',
    privacyLink: 'Privacy Policy',
    privacyUrl: 'https://urgdstudios.com/privacy',
    termsLink: 'Terms of Use',
    termsUrl: 'https://urgdstudios.com/terms',
    closeButton: 'Close',
  },
} as const;
