// All user-facing strings — no hardcoded text in components

export const labels = {
  // Splash entry
  splash: {
    pulseCodeLabel: 'Pulse code',
    pulseCodePlaceholder: 'Enter your pulse code',
    pulseCodeError: "That code doesn\u2019t look right. Check your invitation email.",
    joinButton: 'Join session',
    loginButton: 'Log in',
    signUpButton: 'Sign up',
    backButton: 'Back',
  },

  // Auth — Login
  login: {
    title: 'Sign in to Pulse',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    submitButton: 'Sign in',
    appleButton: 'Continue with Apple',
    googleButton: 'Continue with Google',
    invalidCredentials: 'Incorrect email or password. Try again.',
    newPasswordRequired: 'Setting password for {email}',
    newPasswordLabel: 'New password',
    newPasswordSubmit: 'Set password',
    forgotPassword: 'Forgot password?',
    registrationSuccess: 'Account created. Check your email for a temporary password, then sign in below.',
  },

  // Auth — Register
  register: {
    title: 'Create your account',
    nameLabel: 'Name',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    submitButton: 'Create account',
    verificationTitle: 'Check your email',
    verificationDescription: 'We sent a temporary password to {email}.',
    verificationCodeLabel: 'Verification code',
    verifyButton: 'Verify',
    resendButton: 'Resend code',
    resendCooldown: 'Resend in {seconds}s',
    codeSent: 'Code resent. Check your inbox.',
    invalidCode: "That code isn't right. Check your email and try again.",
    expiredCode: 'That code has expired. Request a new one.',
    emailExists: 'An account with this email already exists.',
    signupClosed: 'Sign-up is currently closed.',
  },

  // Welcome
  welcome: {
    title: 'Welcome to Pulse',
    description:
      'Pulse helps you collect structured feedback on your work through guided AI-driven conversations. Invite reviewers, gather insights, and generate a consolidated Pulse Check — all in one place.',
    ctaButton: 'Create your first item',
    documentTitle: 'Welcome — Pulse',
  },

  // Items
  items: {
    title: 'Items',
    documentTitle: 'Items — Pulse',
    emptyState: 'No items yet',
    newItemButton: 'New Item',
    inviteButton: 'Get Feedback',
    loadError: 'Something went wrong loading your items. Try again.',
    retryButton: 'Retry',
    statusDraft: 'Draft',
    statusActive: 'Active',
    statusClosed: 'Closed',
    statusRevised: 'Revised',
    sessionCount: '{count} sessions',
    closeDate: 'Closes',
  },

  // Item detail
  itemDetail: {
    newDocumentTitle: 'New Item — Pulse',
    editDocumentTitle: '{itemName} — Pulse',
    newHeading: 'New Item',
    editHeading: 'Edit Item',
    fieldName: 'Item name',
    fieldNamePlaceholder: 'Enter item name',
    fieldDescription: 'Feedback focus',
    fieldDescriptionHint: 'This guides the AI conversation. Be specific about what you want reactions to.',
    fieldDescriptionPlaceholder: 'Tell Pulse what kind of feedback you\u2019re looking for \u2014 this shapes the questions reviewers are asked.',
    fieldCloseDate: 'Close date',
    fieldContent: 'Content',
    fieldContentPlaceholder: 'Paste your content here (Markdown supported)',
    fieldContentHint: 'Paste content directly, upload a file, or both.',
    contentPasteLabel: 'Paste content',
    contentUploadLabel: 'Upload a file',
    uploadAcceptHint: 'Accepts .md, .txt, .pdf, .docx — max 10 MB each',
    uploadChooseFile: 'Choose files',
    uploadStatusScanning: 'Scanning…',
    uploadStatusExtracting: 'Extracting…',
    uploadStatusReady: 'Ready',
    uploadStatusRejected: 'Rejected — threat detected',
    uploadStatusExtractionFailed: 'Extraction failed',
    uploadStatusUploading: 'Uploading…',
    uploadStatusError: 'Upload failed',
    saveButton: 'Save',
    cancelButton: 'Cancel',
    deleteButton: 'Delete item',
    lockedError: 'This item is locked and cannot be edited',
    saveError: 'Failed to save item. Please try again.',
    loadError: 'Failed to load item.',
    deleteConfirmTitle: 'Delete item',
    deleteConfirmMessage:
      'Are you sure you want to delete {itemName}? This will also delete all sessions, transcripts, and reports associated with this item.',
    deleteConfirmCancel: 'Cancel',
    deleteConfirmDelete: 'Delete',
    deleteError: 'Failed to delete item. Please try again.',
    readOnlyNotice: 'Items with active or completed sessions can\u2019t be edited to preserve the integrity of reviewer feedback. To make changes, create a new item.',
    previewLink: 'Preview',
    previewAriaLabel: 'Preview {filename}',
    previewCloseAriaLabel: 'Close document preview',
    previewLoading: 'Loading document\u2026',
    previewError: "This document couldn\u2019t be loaded.",
    previewRetry: 'Try again',
    previewEmpty: 'No document to preview.',
    previewExtractedCaption: 'Showing extracted text.',
    previewDownloadOriginal: 'Download original',
    previewPdfFallback: 'Open PDF in new tab \u2192',
    previewNoText: 'No text could be extracted from this file.',
  },

  // Invitation section (within ItemDetail)
  invitation: {
    sectionTitle: 'Reviewers',
    emailsLabel: 'Invite reviewers',
    emailsPlaceholder: 'email@example.com, another@example.com',
    emailsHint: 'Separate multiple emails with commas.',
    inviteButton: 'Invite Reviewers',
    inviting: 'Inviting…',
    inviteSuccess: 'Invitations sent.',
    inviteError: 'Failed to send invitations. Please try again.',
    inviteLimitError: 'Session limit reached for this item.',
    noSessions: 'No reviewers invited yet.',
    resendButton: 'Resend',
    resending: 'Resending…',
    resendSuccess: 'Invitation resent.',
    resendError: 'Failed to resend invitation.',
    statusNotStarted: 'Not started',
    statusInProgress: 'In progress',
    statusCompleted: 'Completed',
    statusExpired: 'Expired',
    extendDeadlineTitle: 'Extend deadline',
    extendDeadlineLabel: 'New close date',
    extendDeadlineButton: 'Extend',
    extending: 'Extending…',
    extendSuccess: 'Deadline extended.',
    extendError: 'Failed to extend deadline.',
    publicSessionTitle: 'Start Public Session',
    publicSessionDescription: 'For use at events, tables, or group settings where a single code is shared.',
    publicSessionDeadlineLabel: 'Session deadline',
    publicSessionGenerateButton: 'Generate',
    publicSessionGenerating: 'Generating…',
    publicSessionDoneButton: 'Done',
    publicSessionError: 'Failed to generate public session. Please try again.',
    publicSessionDownloadQr: 'Download QR code',
    publicSessionViewQr: 'View QR',
    publicSessionHideQr: 'Hide',
    publicSessionBadge: 'Public session',
    publicSessionQrError: 'Failed to load QR code. Try again.',
    closeButton: 'Close',
    publicSessionSectionTitle: 'Public Sessions',
    publicSessionNameLabel: 'Session name',
    publicSessionNamePlaceholder: 'e.g. Design Week Table',
    publicSessionNameHint: 'Optional — helps identify this session if you create multiple.',
    publicSessionEndButton: 'End session',
    publicSessionEnding: 'Ending\u2026',
    publicSessionEndError: 'Failed to end session. Try again.',
    publicSessionEndSuccess: 'Session ended.',
    publicSessionEndsLabel: 'Ends',
    noPublicSessions: 'No public sessions yet.',
  },

  // Settings
  settings: {
    title: 'Settings',
    documentTitle: 'Settings — Pulse',
    accountSection: 'Account',
    tierLabel: 'Plan',
    tierFree: 'Free',
    emailLabel: 'Email',
    displayNameLabel: 'Display name',
    displayNameAdd: 'Add name…',
    displayNamePlaceholder: 'Your name',
    usageSection: 'Usage',
    loading: 'Loading…',
    itemsLabel: 'Items',
    sessionsLabel: 'Sessions',
    itemsUsage: '{used} of {max}',
    sessionsUsage: '{used} of {max}',
    themeSection: 'Appearance',
    themeLabel: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    themeSaving: 'Saving…',
    themeSaved: 'Saved',
    signOutButton: 'Sign out',
    deleteAccountButton: 'Delete account',
    deleteAccountConfirm: 'Confirm — delete my account',
    deleteAccountDeleting: 'Deleting…',
    deleteAccountHint: 'This will permanently delete your account and all data.',
    deleteAccountConfirmHint: 'This cannot be undone. Click again to confirm.',
  },

  // Layout
  layout: {
    navItems: 'Items',
    navPulseCheck: 'Pulse Check',
    navSettings: 'Settings',
    logoAlt: 'ur/gd',
    wordmark: 'pulse',
    themeToggleLight: 'Switch to light mode',
    themeToggleDark: 'Switch to dark mode',
    avatarAlt: 'Account',
  },

  // Protected route
  protectedRoute: {
    redirecting: 'Redirecting to login…',
  },
} as const;
