// Unit tests for UpdateItem Lambda — templateGreeting removal
// Validates: Requirement 13.2 (Phased Cache Priming — template greeting infrastructure removal)
// Updated: templateGreeting is no longer regenerated by the UpdateItem Lambda.
import { describe, it, expect, vi, beforeEach } from 'vitest'

vi.stubEnv('ITEMS_TABLE', 'urgd-pulse-items-dev')
vi.stubEnv('DATA_BUCKET_NAME', 'urgd-pulse-data-dev')
vi.stubEnv('CORS_ALLOWED_ORIGINS', 'https://pulse.urgdstudios.com')
vi.stubEnv('AWS_REGION', 'us-west-2')

const dynamoSendSpy = vi.fn()
const s3SendSpy = vi.fn()
const lambdaSendSpy = vi.fn()

vi.mock('@aws-sdk/client-dynamodb', () => {
  class DynamoDBClient {
    send(...args) { return dynamoSendSpy(...args) }
  }
  class GetItemCommand { constructor(input) { this.input = input } }
  class UpdateItemCommand { constructor(input) { this.input = input } }
  return { DynamoDBClient, GetItemCommand, UpdateItemCommand }
})

vi.mock('@aws-sdk/client-s3', () => {
  class S3Client {
    send(...args) { return s3SendSpy(...args) }
  }
  class PutObjectCommand { constructor(input) { this.input = input } }
  return { S3Client, PutObjectCommand }
})

vi.mock('@aws-sdk/client-lambda', () => {
  class LambdaClient {
    send(...args) { return lambdaSendSpy(...args) }
  }
  class InvokeCommand { constructor(input) { this.input = input } }
  return { LambdaClient, InvokeCommand }
})

// Mock shared modules that have unresolvable dependencies in the test environment
vi.mock('../../lambdas/shared/scheduleClose.mjs', () => ({
  upsertCloseSchedule: vi.fn().mockResolvedValue({}),
  deleteCloseSchedule: vi.fn().mockResolvedValue({}),
}))

const { handler } = await import('../../lambdas/urgd-pulse-updateItem/index.mjs')

function makeEvent({ tenantId = 'tenant-abc', itemId = 'item-xyz', body } = {}) {
  return {
    headers: { origin: 'https://pulse.urgdstudios.com' },
    requestContext: {
      requestId: 'req-test',
      authorizer: tenantId ? { tenantId } : {},
    },
    pathParameters: { itemId },
    body: JSON.stringify(body || {}),
  }
}

function makeExistingItem(overrides = {}) {
  const base = {
    tenantId: { S: 'tenant-abc' },
    itemId: { S: 'item-xyz' },
    itemName: { S: 'Old Name' },
    description: { S: 'A test item.' },
    status: { S: 'draft' },
    createdAt: { S: '2026-01-01T00:00:00.000Z' },
    updatedAt: { S: '2026-01-01T00:00:00.000Z' },
  }
  return { ...base, ...overrides }
}

/** Find the UpdateItemCommand call from dynamoSendSpy */
function findUpdateCall() {
  return dynamoSendSpy.mock.calls
    .map(c => c[0])
    .find(c => c.constructor.name === 'UpdateItemCommand')
}

describe('UpdateItem Lambda — templateGreeting no longer regenerated (R13.2)', () => {
  beforeEach(() => {
    dynamoSendSpy.mockReset()
    s3SendSpy.mockReset()
    lambdaSendSpy.mockReset()
    s3SendSpy.mockResolvedValue({})
    lambdaSendSpy.mockResolvedValue({})
  })

  describe('does not regenerate templateGreeting when itemName changes', () => {
    it('does not include templateGreeting in update even when item has existing greeting', async () => {
      const existingItem = makeExistingItem({
        templateGreeting: { S: 'Old greeting text' },
        itemType: { S: 'document' },
      })

      dynamoSendSpy.mockImplementation((cmd) => {
        if (cmd.constructor.name === 'GetItemCommand') {
          return Promise.resolve({ Item: existingItem })
        }
        return Promise.resolve({ Attributes: {
          ...existingItem,
          itemName: { S: 'New Name' },
          updatedAt: { S: new Date().toISOString() },
        }})
      })

      const result = await handler(makeEvent({
        body: { itemName: 'New Name' },
      }))

      expect(result.statusCode).toBe(200)

      const updateCall = findUpdateCall()
      expect(updateCall).toBeDefined()

      // templateGreeting should NOT be in the update
      const values = updateCall.input.ExpressionAttributeValues
      expect(values[':templateGreeting']).toBeUndefined()
      expect(updateCall.input.UpdateExpression).not.toContain('templateGreeting')
    })
  })

  describe('items without existing templateGreeting still work', () => {
    it('updates itemName without touching templateGreeting', async () => {
      const existingItem = makeExistingItem({
        itemType: { S: 'document' },
        // no templateGreeting field
      })

      dynamoSendSpy.mockImplementation((cmd) => {
        if (cmd.constructor.name === 'GetItemCommand') {
          return Promise.resolve({ Item: existingItem })
        }
        return Promise.resolve({ Attributes: {
          ...existingItem,
          itemName: { S: 'Updated Name' },
          updatedAt: { S: new Date().toISOString() },
        }})
      })

      const result = await handler(makeEvent({
        body: { itemName: 'Updated Name' },
      }))

      expect(result.statusCode).toBe(200)

      const updateCall = findUpdateCall()
      const values = updateCall.input.ExpressionAttributeValues
      expect(values[':templateGreeting']).toBeUndefined()
    })
  })
})
